spring:
  application:
    name: sample1
  datasource:
    url: jdbc:mysql://localhost:3306/samplespringbootdb?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: your_super_secret_jwt_key_that_is_long_enough_for_HS512_as_it_must_have_a_size_greater_than_512_bits
  expiration: 86400000